<?php

namespace AppBundle\Repository;

/**
 * Plus78ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Plus78ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
