<?php

namespace AppBundle\Repository;

/**
 * Plus78ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Plus78ApartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMaxDatetime()
    {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(
            'SELECT max(p.updated_at)
        FROM AppBundle\Entity\Plus78Apartment p'
        );
        return $query->execute();
    }
}
