<?php

namespace AppBundle\Repository;

/**
 * Plus78FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Plus78FlatRepository extends \Doctrine\ORM\EntityRepository
{
}
