<?php

namespace AppBundle\Repository;

/**
 * Plus78BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Plus78BlockRepository extends \Doctrine\ORM\EntityRepository
{
}
