<?php

namespace AppBundle\Repository;

/**
 * Plus78BuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Plus78BuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
